---
repos:
  -
    repo: https://github.com/ambv/black
    rev: stable
    hooks:
      -
        id: black
        language_version: python3.6
  -
    repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.4
    hooks:
      -
        id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-comprehensions
          - flake8-rst
          - pep8-naming
  -
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.660
    hooks:
      -
        id: mypy
  -
    # Use the pylint mirror until issue with black is solved
    # (https://github.com/PyCQA/pylint/issues/289).
    repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.2.2
    hooks:
      - id: pylint
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-yaml
